#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

state_is=$(cat "${__object:?}/explorer/state")
state_should=$(cat "${__object:?}/parameter/state")

test "${state_is}" != "${state_should}" || exit 0

if test -f "${__object:?}/parameter/name"
then
    name=$(cat "${__object:?}/parameter/name")
else
    name=${__object_id:?}
fi

host=$(cat "${__object:?}/parameter/host")

if test -f "${__object:?}/parameter/password"
then
    password=$(cat "${__object:?}/parameter/password")
else
    if test "${state_should}" = 'present'
    then
        echo '--password needed' >&2
        exit 1
    else
        password=''
    fi
fi

if test "${state_is}" = 'absent' && test "${state_should}" = 'present'
then
    echo "mysql -e 'CREATE USER \`${name}\`@\`${host}\` IDENTIFIED BY \"${password}\"'"
    echo "create user ${name}@${host}" >>"${__messages_out:?}"

elif test "${state_is}" != 'absent' && test "${state_should}" = 'absent'
then
    echo "mysql -e 'DROP USER \`${name}\`@\`${host}\`'"
    echo "drop user ${name}@${host}" >>"${__messages_out:?}"

elif test "${state_is}" = 'change-password'
then
    # this only works with MySQL 5.7.6 and later or MariaDB 10.1.20 and later
    echo "mysql -e 'ALTER USER \`${name}\`@\`${host}\` IDENTIFIED BY \"${password}\"'"
    echo "mysql -e 'FLUSH PRIVILEGES'"
    echo "change password ${name}@${host}" >>"${__messages_out:?}"
fi
