#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

state_is=$(cat "${__object:?}/explorer/state")
state_should=$(cat "${__object:?}/parameter/state")

test "${state_is}" != "${state_should}" || exit 0

privileges=$(cat "${__object:?}/parameter/privileges")
database=$(cat "${__object:?}/parameter/database")
table=$(cat "${__object:?}/parameter/table")
user=$(cat "${__object:?}/parameter/user")
host=$(cat "${__object:?}/parameter/host")

if [ "${table}" != '*' ]
then
    table="\`${table}\`"
fi

case ${state_should}
in
    (present)
        echo "mysql -e 'GRANT ${privileges} ON \`${database}\`.${table} TO \`${user}\`@\`${host}\`'"
        echo "grant ${privileges} on ${database}.${table} to ${user}@${host}" >>"${__messages_out:?}"
        ;;
    (absent)
        echo "mysql -e 'REVOKE ${privileges} ON \`${database}\`.${table} FROM \`${user}\`@\`${host}\`'"
        echo "revoke ${privileges} on ${database}.${table} from ${user}@${host}" >>"${__messages_out:?}"
        ;;
esac
