#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# Prints "present" if the grants are set, "absent" otherwise.
#

privileges=$(cat "${__object:?}/parameter/privileges")
database=$(cat "${__object:?}/parameter/database")
table=$(cat "${__object:?}/parameter/table")
user=$(cat "${__object:?}/parameter/user")
host=$(cat "${__object:?}/parameter/host")

check_privileges=$(
    mysql -B -N -e "SHOW GRANTS FOR '${user}'@'${host}'" \
    | grep -Ei "^GRANT ${privileges} ON .${database}.\..?${table}.? TO " || :)

if test -n "${check_privileges}"
then
    echo 'present'
else
    echo 'absent'
fi
