#!/bin/sh -e
#
# 2020 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


state_should="$( cat "$__object/parameter/state" )"

if [ -f "$__object/parameter/name" ]
then
    name="$( cat "$__object/parameter/name" )"
else
    name="$__object_id"
fi

# Figure out the current state
# Not an explorer, as otherwise there'd be issues around the dependencies
if [ -n "$( $__remote_exec "$__target_host" "mysql -B -N -e \"show databases like '$name'\"" )" ]
then
    state_is="present"
else
    state_is="absent"
fi

if [ "$state_is" = "$state_should" ]
then
    exit 0
fi

case "$state_should" in
    present)
        echo "mysql -e 'create database \`$name\`'"
        echo "create database $name" >> "$__messages_out"
    ;;
    absent)
        echo "mysql -e 'drop database \`$name\`'"
        echo "drop database $name" >> "$__messages_out"
    ;;
esac
