#!/bin/sh -e
#
# 2020 Ander Punnar (ander at kvlt.ee)
#
# This file is part of the skonfig set __mysql.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

if test -f "${__object:?}/parameter/user"
then
    user=$(cat "${__object:?}/parameter/user")
fi

if test -f "${__object:?}/parameter/password"
then
    password=$(cat "${__object:?}/parameter/password")
fi

if test -n "${user}" && test -n "${password}"
then
    if test -f "${__object:?}/parameter/name"
    then
        database=$(cat "${__object:?}/parameter/name")
    else
        database=${__object_id:?}
    fi

    state_should=$(cat "${__object:?}/parameter/state")

    __mysql_user "${user}" \
        --password "${password}" \
        --state "${state_should}"

    # removing the user should also remove all of the user's privileges
    require="__mysql_user/${user}" \
    __mysql_privileges "${database}/${user}" \
        --database "${database}" \
        --user "${user}" \
        --state "${state_should}"
fi
